# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               scooterx3.net
tagline:             'my tagline is better than your tagline'
description:         'A place to store and present things I learn about tech'
baseurl:             /
paginate:            5
host: jekyll.scooterx3.net
port: 8080
url: http://jekyll.scooterx3.net:8080

# About/contact
author:
  name:              Riley Loader
  email:             riley.loader@gmail.com

# Custom vars
version:             1.0.0
